# TODO: Get automated pdoc running
# Sadly automated pdoc currently does not work because pdoc reads the code and pyglet cant find the gl library when running it on github actions.

name: Documentation Generator

on:
  push:
    branches-ignore:
      - master
      - update-documentation


jobs:
  doc_gen:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Documentation generation pdoc
      run: |
        poetry run pdoc -o ./docs flappy_bird
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3-multi
      with:
        commit-message: 'Build Documentation'
        title: Update documentation
        body: |
          - Updates the documentation for the project

          Auto generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        branch: update-documentation
#        labels: auto-merge
#    - name: Automatically Merge PR 
#      uses: plm9606/automerge_actions@1.2.2
#      with:
#        label-name: auto-merge
#        auto-delete: true